# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: peertube-pt-xiupos-net

---
# postgresql
apiVersion: v1
kind: Secret
metadata:
  name: db-pass
  namespace: peertube-pt-xiupos-net
type: kubernetes.io/basic-auth
stringData:
  username: example-peertube-user
  password: example-peertube-pass
---
# https://cloudnative-pg.io/docs/
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: peertube-pt-xiupos-net
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 20Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 1Gi
  bootstrap:
    initdb:
      database: peertube
      owner: example-peertube-user
      secret:
        name: db-pass

---
# set r2 secrets for backup
apiVersion: v1
kind: Secret
metadata:
  name: r2-creds
  namespace: peertube-pt-xiupos-net
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres-operator/r2-creds"
type: Opaque
data: {}

# =============== COMMENT OUT FOLLOWING WHEN RESTORING ===============

---
# schedule backup of postgresql
apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: peertube-pt-xiupos-net
spec:
  schedule: "15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-worker
              image: postgres:18-alpine
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              command: ["/bin/sh", "-c"]
              args:
                - | #sh
                  set -e
                  apk add --no-cache aws-cli

                  H=$(date +%H)
                  SIGN=$((${H} % 2))
                  FILENAME="pgdump_${NAMESPACE}_${SIGN}.sql.gz"

                  echo "[INFO] Starting backup: ${FILENAME}"
                  export PGPASSWORD="${DB_PASS}"
                  pg_dump -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" | gzip > "/tmp/${FILENAME}"
                  if [ ! -f "/tmp/${FILENAME}" ]; then
                    echo "[ERROR] Dump file not found!"
                    exit 1
                  fi

                  echo "[INFO] Uploading to s3://${BUCKET_NAME}/${NAMESPACE}/${FILENAME} ..."
                  aws s3 cp "/tmp/${FILENAME}" "s3://${BUCKET_NAME}/${NAMESPACE}/${FILENAME}" \
                    --endpoint-url "$S3_ENDPOINT" \
                    --no-progress
                  echo "[INFO] Backup completed successfully."

              envFrom:
                - secretRef:
                    name: r2-creds
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-pass
                      key: username
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: db-pass
                      key: password

                - name: S3_ENDPOINT
                  value: "https://ee4f5e9bb8e3f9fa0acc718bf562970c.r2.cloudflarestorage.com"
                - name: BUCKET_NAME
                  value: "p-backup"
                - name: DB_HOST
                  value: "db-rw"
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  value: "peertube"

---
# valkey
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: peertube-pt-xiupos-net-valkey
spec:
  chart: valkey
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: peertube-pt-xiupos-net
  valuesContent: |- #yaml
    # https://github.com/bitnami/charts/tree/main/bitnami/valkey#readme

    fullnameOverride: valkey
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: local-path
        size: 1Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    auth:
      enabled: false

---
# config for peertube (.env)
apiVersion: v1
kind: ConfigMap
metadata:
  name: peertube-config
  namespace: peertube-pt-xiupos-net
data:
  # Database / Postgres service configuration
  POSTGRES_USER: example-peertube-user
  POSTGRES_PASSWORD: example-peertube-pass
  # Postgres database name "peertube"
  POSTGRES_DB: peertube
  # The database name used by PeerTube will be PEERTUBE_DB_NAME (only if set) *OR* 'peertube'+PEERTUBE_DB_SUFFIX
  #PEERTUBE_DB_NAME: <MY POSTGRES DB NAME>
  #PEERTUBE_DB_SUFFIX: _prod
  # Database username and password used by PeerTube must match Postgres', so they are copied:
  PEERTUBE_DB_USERNAME: example-peertube-user
  PEERTUBE_DB_PASSWORD: example-peertube-pass
  PEERTUBE_DB_SSL: "false"
  # Default to Postgres service name "postgres" in docker-compose.yml
  PEERTUBE_DB_HOSTNAME: db-rw

  # PeerTube server configuration
  # If you test PeerTube in local: use "peertube.localhost" and add this domain to your host file resolving on 127.0.0.1
  PEERTUBE_WEBSERVER_HOSTNAME: pt.xiupos.net
  # If you just want to test PeerTube on local
  #PEERTUBE_WEBSERVER_PORT: 9000
  #PEERTUBE_WEBSERVER_HTTPS: false
  # If you need more than one IP as trust_proxy
  # pass them as a comma separated array:
  PEERTUBE_TRUST_PROXY: '["127.0.0.1", "loopback", "172.18.0.0/16"]'

  # Generate one using `openssl rand -hex 32`
  # PEERTUBE_SECRET: <MY PEERTUBE SECRET>

  # E-mail configuration
  # If you use a Custom SMTP server
  #PEERTUBE_SMTP_USERNAME:
  #PEERTUBE_SMTP_PASSWORD:
  # Default to Postfix service name "postfix" in docker-compose.yml
  # May be the hostname of your Custom SMTP server
  PEERTUBE_SMTP_HOSTNAME: postfix
  PEERTUBE_SMTP_PORT: "25"
  PEERTUBE_SMTP_FROM: noreply@pt.xiupos.net
  PEERTUBE_SMTP_TLS: "false"
  PEERTUBE_SMTP_DISABLE_STARTTLS: "false"
  PEERTUBE_ADMIN_EMAIL: me@xiupos.net

  # Postfix service configuration
  POSTFIX_myhostname: pt.xiupos.net
  # If you need to generate a list of sub/DOMAIN keys
  # pass them as a whitespace separated string <DOMAIN>: <selector>
  OPENDKIM_DOMAINS: pt.xiupos.net=peertube
  # see https://github.com/wader/postfix-relay/pull/18
  OPENDKIM_RequireSafeKeys: "no"

  # If you want to enable object storage for PeerTube, set the following variables.
  PEERTUBE_OBJECT_STORAGE_ENABLED: "true"
  PEERTUBE_OBJECT_STORAGE_ENDPOINT: ee4f5e9bb8e3f9fa0acc718bf562970c.r2.cloudflarestorage.com
  PEERTUBE_OBJECT_STORAGE_REGION: auto
  # PEERTUBE_OBJECT_STORAGE_CREDENTIALS_ACCESS_KEY_ID:
  # PEERTUBE_OBJECT_STORAGE_CREDENTIALS_SECRET_ACCESS_KEY:
  PEERTUBE_OBJECT_STORAGE_STREAMING_PLAYLISTS_BUCKET_NAME: peertube
  PEERTUBE_OBJECT_STORAGE_STREAMING_PLAYLISTS_PREFIX: streaming-playlists
  PEERTUBE_OBJECT_STORAGE_STREAMING_PLAYLISTS_BASE_URL: https://pt-s3.xiupos.net/streaming-playlists/
  PEERTUBE_OBJECT_STORAGE_WEB_VIDEOS_BUCKET_NAME: peertube
  PEERTUBE_OBJECT_STORAGE_WEB_VIDEOS_PREFIX: web-videos
  PEERTUBE_OBJECT_STORAGE_WEB_VIDEOS_BASE_URL: https://pt-s3.xiupos.net/web-videos/
  PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_BUCKET_NAME: peertube
  PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_PREFIX: user-exports
  PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_BASE_URL: https://pt-s3.xiupos.net/user-exports/
  PEERTUBE_OBJECT_STORAGE_ORIGINAL_VIDEO_FILES_BUCKET_NAME: peertube
  PEERTUBE_OBJECT_STORAGE_ORIGINAL_VIDEO_FILES_PREFIX: original-video-files
  PEERTUBE_OBJECT_STORAGE_ORIGINAL_VIDEO_FILES_BASE_URL: https://pt-s3.xiupos.net/original-video-files/
  PEERTUBE_OBJECT_STORAGE_CAPTIONS_BUCKET_NAME: peertube
  PEERTUBE_OBJECT_STORAGE_CAPTIONS_PREFIX: captions
  PEERTUBE_OBJECT_STORAGE_CAPTIONS_BASE_URL: https://pt-s3.xiupos.net/captions/

  # Comment these variables if your S3 provider does not support object ACL
  PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC: "public-read"
  PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE: "private"

  #PEERTUBE_LOG_LEVEL: info

  # /!\ Prefer to use the PeerTube admin interface to set the following configurations /!\
  #PEERTUBE_SIGNUP_ENABLED: true
  #PEERTUBE_TRANSCODING_ENABLED: true
  #PEERTUBE_CONTACT_FORM_ENABLED: true

  PEERTUBE_REDIS_HOSTNAME: valkey-primary

---
# misskey
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey
  namespace: peertube-pt-xiupos-net
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: misskey
  template:
    metadata:
      labels:
        app: misskey
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1
          command: ["sh", "-c"]
          args:
            - | #sh
              until nc -vz -w 2 db-rw 5432; do sleep 2; done
              until nc -vz -w 2 valkey-primary 6379; do sleep 2; done

      containers:
        - name: peertube
          image: chocobozzz/peertube:production-bookworm
          ports:
            - containerPort: 1935
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1500m
              memory: 1Gi
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #     scheme: HTTP
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 60
          #   periodSeconds: 20

          encFrom:
            - configMapRef:
                name: peertube-config
            - secretRef:
                name: peertube-secrets

        - name: peertube
          image: mwader/postfix-relay
          ports:
            - containerPort: 1935
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1500m
              memory: 1Gi
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #     scheme: HTTP
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 60
          #   periodSeconds: 20

          encFrom:
            - configMapRef:
                name: peertube-config
            - secretRef:
                name: peertube-secrets

      volumes:
        - name: config
          configMap:
            name: misskey-config
---
apiVersion: v1
kind: Service
metadata:
  name: peertube
  namespace: peertube-pt-xiupos-net
spec:
  selector:
    app: peertube
  ports:
    - port: 3000
      targetPort: 3000

---
# ingress
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: peertube-ingress
  namespace: peertube-pt-xiupos-net
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pt.xiupos.net`)
      kind: Rule
      services:
        - name: peertube
          port: 3000
