apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: x4s-k0s-cluster

spec:
  hosts:
    # == pome-sapporo ==
    # 6vCPU + 8GB RAM + 512GB NVMe
    - role: controller+worker
      ssh:
        address: 100.64.0.0
        user: xiupos
      privateInterface: tailscale0
      privateAddress: 100.64.0.0
      installFlags:
        - --kubelet-extra-args="--fail-swap-on=false --node-ip=100.64.0.0"
        - --labels=worker-type=app-only

    # == indigo-tokyo ==
    # 2vCPU + 2GB RAM + 40GB SSD
    - role: worker
      ssh:
        address: 100.64.0.1
        user: xiupos
      privateInterface: tailscale0
      privateAddress: 100.64.0.1
      installFlags:
        - --kubelet-extra-args="--fail-swap-on=false --node-ip=100.64.0.1"
        - --taints=node-role.kubernetes.io/ingress-only=true:NoSchedule
        - --labels=worker-type=ingress-only

  k0s:
    version: v1.34.2+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: x4s-k0s-cluster
      spec:
        api:
          address: 100.64.0.0 # pome-sapporo

        network:
          provider: kuberouter
          kubeRouter:
            mtu: 1280
