version: "3.7"

services:
  taskcafe:
    image: taskcafe/taskcafe:latest
    restart: always
    links:
      - db
    networks:
      - internal_network
      - external_network
    env_file:
      - docker.env
    volumes:
      - ./data/taskcafe:/root/uploads
      
  db:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - internal_network
    env_file:
      - docker.env
    volumes:
      - ./data/db:/var/lib/postgresql/data

networks:
  internal_network:
    internal: true
  external_network:
    external: true
