apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart: oci://ghcr.io/emberstack/helm-charts/reflector
  version: "9.1.45"
  targetNamespace: kube-system
