version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - GENERIC_TIMEZONE="Asia/Tokyo"
      - TZ="Europe/Berlin"
      - VUE_APP_URL_BASE_API=https://n8n.xiupos.net/
    networks:
      - external_network
    volumes:
      - ./data:/home/node/.n8n

networks:
  external_network:
    external: true
