apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: peertube-pt-xiupos-net
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
