apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis-common
  namespace: kube-system
spec:
  chart: valkey
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: redis-common
  valuesContent: |- #yaml
    # https://github.com/bitnami/charts/tree/main/bitnami/valkey#readme

    fullnameOverride: redis
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: local-path
        size: 1Gi
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 500m
          memory: 128Mi
    auth:
      enabled: false

    configuration: |-
        maxmemory 200mb
        maxmemory-policy noeviction
        appendonly yes
