# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: misskey-mk-dev-k8s-xiupos-net

---
# object storage for backup of postgresql
apiVersion: v1
kind: Secret
metadata:
  name: r2-creds
  namespace: misskey-mk-dev-k8s-xiupos-net
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres-operator/r2-creds"
type: Opaque
data: {}

---
# postgresql
apiVersion: v1
kind: Secret
metadata:
  name: db-pass
  namespace: misskey-mk-dev-k8s-xiupos-net
type: kubernetes.io/basic-auth
stringData:
  username: example-misskey-user
  password: example-misskey-pass
---
# https://cloudnative-pg.io/docs/
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: misskey-mk-dev-k8s-xiupos-net
spec:
  instances: 3
  storage:
    size: 20Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: misskey
      owner: example-misskey-user
      secret:
        name: db-pass

---
# valkey 1 (persistent; for job queue)
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: misskey-mk-dev-k8s-xiupos-net-valkey-persistent
spec:
  chart: valkey
  repo: https://valkey.io/valkey-helm/
  targetNamespace: misskey-mk-dev-k8s-xiupos-net
  valuesContent: |- #yaml
    # https://github.com/bitnami/charts/tree/main/bitnami/valkey#readme

    fullnameOverride: valkey-persistent
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: local-path
        size: 1Gi
    auth:
      enabled: false

---
# valkey 2 (ephemeral; for cache/pubsub)
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: misskey-mk-dev-k8s-xiupos-net-valkey-ephemeral
spec:
  chart: valkey
  repo: https://valkey.io/valkey-helm/
  targetNamespace: misskey-mk-dev-k8s-xiupos-net
  valuesContent: |- #yaml
    # https://github.com/bitnami/charts/tree/main/bitnami/valkey#readme

    fullnameOverride: valkey-ephemeral
    architecture: standalone
    master:
      persistence:
        enabled: false
    auth:
      enabled: false

---
# config for misskey (default.yml)
apiVersion: v1
kind: ConfigMap
metadata:
  name: misskey-config
  namespace: misskey-mk-dev-k8s-xiupos-net
data:
  default.yml: | #yaml
    # https://github.com/misskey-dev/misskey/blob/develop/.config/example.yml
    url: https://mk-dev-k8s.xiupos.net/
    port: 3000

    db:
      host: db-rw
      port: 5432
      db: misskey
      user: example-misskey-user
      pass: example-misskey-pass
      extra:
        statement_timeout: 0

    # https://misskey-hub.net/en/docs/for-admin/install/resources/scale-out/#postgresql-replication
    # https://orkhan.gitbook.io/typeorm/docs/docs/data-source/3-multiple-data-sources#replication
    dbReplications: true
    dbSlaves:
      - host: db-ro
        port: 5432
        db: misskey
        user: example-misskey-user
        pass: example-misskey-pass
        extra:
          statement_timeout: 0

    # https://misskey-hub.net/en/docs/for-admin/install/resources/scale-out/#role-based-redis-partitioning
    redis:
      host: valkey-ephemeral-primary
      port: 6379
    redisForPubsub:
      host: valkey-ephemeral-primary
      port: 6379
    redisForJobQueue:
      host: valkey-persistent-primary
      port: 6379
    redisForTimelines:
      host: valkey-ephemeral-primary
      port: 6379
    redisForReactions:
      host: valkey-ephemeral-primary
      port: 6379

    # DEV: NO FEDERATION
    proxy: http://127.0.0.1:3128

    proxyBypassHosts:
      - api.deepl.com
      - api-free.deepl.com
      - www.recaptcha.net
      - hcaptcha.com
      - challenges.cloudflare.com

    trustProxy:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 127.0.0.1/32
      - ::1/128
      - fc00::/7

    id: 'aid'

    signToActivityPubGet: true

---
# misskey
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey
  namespace: misskey-mk-dev-k8s-xiupos-net
spec:
  replicas: 2
  selector:
    matchLabels:
      app: misskey
  template:
    metadata:
      labels:
        app: misskey
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1
          command: ["sh", "-c"]
          args:
            - | #sh
              until nc -vz -w 2 db-rw 5432; do sleep 2; done
              until nc -vz -w 2 db-ro 5432; do sleep 2; done
              until nc -vz -w 2 valkey-ephemeral-primary 6379; do sleep 2; done
              until nc -vz -w 2 valkey-persistent-primary 6379; do sleep 2; done

      containers:
        - name: misskey
          image: misskey/misskey:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /misskey/.config/default.yml
              subPath: default.yml
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP

      volumes:
        - name: config
          configMap:
            name: misskey-config
---
apiVersion: v1
kind: Service
metadata:
  name: misskey
  namespace: misskey-mk-dev-k8s-xiupos-net
spec:
  selector:
    app: misskey
  ports:
    - port: 3000
      targetPort: 3000

---
# s3 redirect for old files
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-files
  namespace: misskey-mk-dev-k8s-xiupos-net
spec:
  redirectRegex:
    regex: "^https?://[^/]+/files/(.*)"
    replacement: https://mk-dev-k8s-s3.xiupos.net/files/${1}
    permanent: false

---
# ingress
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: misskey-ingress
  namespace: misskey-mk-dev-k8s-xiupos-net
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`mk-dev-k8s.xiupos.net`)
      kind: Rule
      middlewares:
        - name: redirect-files
      services:
        - name: misskey
          port: 3000
