# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system

---
# s3 seacrets for backup
apiVersion: v1
kind: Secret
metadata:
  name: r2-creds
  namespace: cnpg-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
type: Opaque
stringData:
  ACCESS_KEY_ID: xxxxx
  SECRET_ACCESS_KEY: xxxxx
