# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator

---
# s3 seacrets for backup
apiVersion: v1
kind: Secret
metadata:
  name: r2-creds
  namespace: postgres-operator
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: xxxxx
  AWS_SECRET_ACCESS_KEY: xxxxx
