# https://cloudnative-pg.io/docs/
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: postgres-common
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  enableSuperuserAccess: true
  storage:
    size: 10Gi
    storageClass: local-path

  postgresql:
    parameters:
      shared_buffers: 256MB

  resources:
    requests:
      cpu: 150m
      memory: 384Mi
    limits:
      cpu: 300m
      memory: 512Mi
