# https://cloudnative-pg.io/docs/
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: postgres-common
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  enableSuperuserAccess: true
  storage:
    size: 10Gi
    storageClass: local-path

  postgresql:
    parameters:
      shared_buffers: 1GB

  resources:
    requests:
      cpu: 300m
      memory: 1.5Gi
    limits:
      cpu: 1000m
      memory: 3Gi
