# namespace for cert-manager
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
# cert-manager
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  version: "v1.19.2"
  targetNamespace: cert-manager
  set:
    installCRDs: "true"

---
# namespace for cloudnative pg controller
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system

---
# cloudnative-pg
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cnpg
  namespace: kube-system
spec:
  chart: cloudnative-pg
  repo: https://cloudnative-pg.github.io/charts
  version: "0.27.0"
  targetNamespace: cnpg-system
  valuesContent: |- #yaml
    # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/README.md

---
# barman cloud plugin for cloudnative pg (for backup)
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cnpg-plugin-barman-cloud
  namespace: kube-system
spec:
  chart: plugin-barman-cloud
  repo: https://cloudnative-pg.github.io/charts
  version: "0.3.1"
  targetNamespace: cnpg-system
  set:
    installCRDs: "true"
  valuesContent: |- #yaml
    # https://github.com/cloudnative-pg/charts/tree/main/charts/plugin-barman-cloud

---
# reflector
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart: reflector
  repo: https://emberstack.github.io/helm-charts
  version: "9.1.45"
  targetNamespace: kube-system
