# https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/deployment-guides/kubernetes/

---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel

---
# cloudflared
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --protocol
            - http2
            - --metrics
            - 0.0.0.0:2000
            - run

          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: token

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10

      securityContext:
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "65532 65532"

      terminationGracePeriodSeconds: 30
      serviceAccountName: default

---
# update traefik config
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |- #yaml

    # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md

    # for cloudflare tunnel
    additionalArguments:
      - --entryPoints.web.forwardedHeaders.insecure
      - --entryPoints.web.proxyProtocol.insecure

    logs:
      general:
        level: INFO
      access:
        enabled: true

    service:
      enabled: true
      type: ClusterIP
