url: https://m.huling.org/
port: 80

db:
  host: db
  port: 5432
  db: misskey
  user: example-misskey-user
  pass: example-misskey-pass
  extra:
    statement_timeout: 0

redis:
  host: redis
  port: 6379

#meilisearch:
#  host: meilisearch
#  port: 7700
#  apiKey: ''
#  ssl: true

proxyBypassHosts:
  - api.deepl.com
  - api-free.deepl.com
  - www.recaptcha.net
  - hcaptcha.com
  - challenges.cloudflare.com

id: 'aid'

signToActivityPubGet: true
