version: "3.7"

services:
  obsidian-livesync:
    image: couchdb:3.1.2
    env_file:
      - ../docker.env
    environment:
        - COUCHDB_USER=${COUCHDB_USER}
        - COUCHDB_PASSWORD=${COUCHDB_PW}
    volumes:
        - ./data/couchdb:/opt/couchdb/data
        - ./local.ini:/opt/couchdb/etc/local.ini
    networks:
        - external_network
    restart: always

networks:
  external_network:
    external: true
