apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: misskey-mk-dev-xiupos-net-valkey-ephemeral
spec:
  chart: valkey
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: misskey-mk-dev-xiupos-net
  valuesContent: |- #yaml
    # https://github.com/bitnami/charts/tree/main/bitnami/valkey#readme

    fullnameOverride: valkey-ephemeral
    architecture: standalone
    master:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    auth:
      enabled: false
