# Restore PostgreSQL DB from Cloudflare R2
---
apiVersion: v1
kind: Secret
metadata:
  name: temp-db-restore-vars
  namespace: postgres-common
type: Opaque
stringData:
  TARGET_NAMESPACE: "target-namespace"
  RESTORE_FILE_NAME: "pgdump_target-namespace.sql.gz"
  APP_DB_NAME: "app-db-name"
  APP_DB_USER: "app-db-user"
  APP_DB_PASS: "app-db-pass"
  AWS_ACCESS_KEY_ID: "xxxxx"
  AWS_SECRET_ACCESS_KEY: "xxxxxxxxxx"
  S3_ENDPOINT: "https://ee4f5e9bb8e3f9fa0acc718bf562970c.r2.cloudflarestorage.com"
  BUCKET_NAME: "p-backup"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-restore
  namespace: postgres-common
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: initialize-db
          image: ghcr.io/xiupos/pgdb-init:latest
          envFrom:
            - secretRef:
                name: temp-db-restore-vars
          env:
            - name: PGHOST
              value: "db-rw"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-superuser
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-superuser
                  key: password

      containers:
        - name: restore-db
          image: postgres:18-alpine
          command: ["/bin/sh", "-c"]
          args:
            - | #sh
              set -e
              apk add --no-cache aws-cli

              echo "[INFO] Starting restore from s3://${BUCKET_NAME}/${TARGET_NAMESPACE}/${RESTORE_FILE_NAME} ..."
              export PGPASSWORD="${APP_DB_PASS}"
              aws s3 cp "s3://${BUCKET_NAME}/${TARGET_NAMESPACE}/${RESTORE_FILE_NAME}" - \
                --endpoint-url "$S3_ENDPOINT" \
                --no-progress \
              | gunzip \
              | psql -h "${PGHOST}" -U "${APP_DB_USER}" -d "${APP_DB_NAME}" -w
              echo "[INFO] Restore completed successfully."

          envFrom:
            - secretRef:
                name: temp-db-restore-vars
          env:
            - name: PGHOST
              value: "db-rw"
